require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/ebooks", type: :request do
  
  # Ebook. As you add validations to Ebook, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Ebook.create! valid_attributes
      get ebooks_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      ebook = Ebook.create! valid_attributes
      get ebook_url(ebook)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_ebook_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      ebook = Ebook.create! valid_attributes
      get edit_ebook_url(ebook)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Ebook" do
        expect {
          post ebooks_url, params: { ebook: valid_attributes }
        }.to change(Ebook, :count).by(1)
      end

      it "redirects to the created ebook" do
        post ebooks_url, params: { ebook: valid_attributes }
        expect(response).to redirect_to(ebook_url(Ebook.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Ebook" do
        expect {
          post ebooks_url, params: { ebook: invalid_attributes }
        }.to change(Ebook, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post ebooks_url, params: { ebook: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested ebook" do
        ebook = Ebook.create! valid_attributes
        patch ebook_url(ebook), params: { ebook: new_attributes }
        ebook.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the ebook" do
        ebook = Ebook.create! valid_attributes
        patch ebook_url(ebook), params: { ebook: new_attributes }
        ebook.reload
        expect(response).to redirect_to(ebook_url(ebook))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        ebook = Ebook.create! valid_attributes
        patch ebook_url(ebook), params: { ebook: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested ebook" do
      ebook = Ebook.create! valid_attributes
      expect {
        delete ebook_url(ebook)
      }.to change(Ebook, :count).by(-1)
    end

    it "redirects to the ebooks list" do
      ebook = Ebook.create! valid_attributes
      delete ebook_url(ebook)
      expect(response).to redirect_to(ebooks_url)
    end
  end
end
